# Generated by Django 3.0.7 on 2021-02-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Professor',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Student',
        ),
    ]
