# Generated by Django 3.0.7 on 2021-02-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210218_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
