# Generated by Django 3.0.7 on 2021-02-20 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_professor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_student',
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
